import type { Metadata } from "next";
// import  font and styles
import { Inter } from "next/font/google";
import "./globals.css";
// import SideBar
import SideBar from "./(components)/SideBar/SideBar";

const inter = Inter({ subsets: ["latin"] });

// get year
const today = new Date();
const year = today.getFullYear();

//get name
const name = "Veronika Kolesnikova";

export const metadata: Metadata = {
  title: "Plant Parent App",
  description: "Generated by Veronika Kolesnikova",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SideBar  />
        {children}
        <footer>&copy; {name}, {year}</footer>
        </body>
    </html>
  );
}
